image: node:12.13.0-alpine
before_script:
  - npm i -g firebase-tools
deploy-hosting:
  stage: deploy
  script:
    - yarn
    - yarn build
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - master